# Generated by Django 4.1.5 on 2023-01-14 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='static/music')),
                ('cover', models.ImageField(upload_to='static/images')),
                ('poster', models.ImageField(upload_to='static/images')),
                ('duration', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=250)),
                ('singer', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
