# Generated by Django 4.1.5 on 2023-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_artist_remove_music_singer_music_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
