# Generated by Django 4.1.5 on 2023-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_artist_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
