
# Generated by Django 4.1.5 on 2023-01-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_phone_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
