# Generated by Django 4.1.5 on 2023-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
